site_name: Tritask
use_directory_urls: false
docs_dir: src
site_dir: docs
theme:
  name: 'material'
  language: 'ja'
markdown_extensions:
    - toc:
        permalink: True
    - mdx_truly_sane_lists:
        nested_indent: 2
extra:
  search:
    language: 'jp'